rs_rujukan/urls.py
from django.urls import path

from . import views

app_name = 'rs_rujukan'

urlpatterns = [
    path('', views.index, name='index'),
    path('results', views.search, name='search')
]

situs/urls.py
from django.urls import path

from . import views

app_name = 'situs'

urlpatterns = [
    path('', views.situs, name='situs'),
    path('savepesan/', views.pesan, name='pesan'),
]

tk1_ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beranda.urls')),
    path('rs-rujukan/', include('rs_rujukan.urls')),
    path('donasi/', include('donasi.urls')),
    path('situs/', include('situs.urls')),
]

rs_rujukan/models.py
from django.db import models

class RumahSakit(models.Model):
    name = models.CharField(max_length=100)
    province = models.CharField(max_length=50)
    address = models.TextField()
    telp = models.CharField(max_length=50)

    def __str__(self):
        return self.name

rs_rujukan/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .models import RumahSakit

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

content = {}

def index(request):
    content['rumah_sakit'] = []
    list_rumahsakit = RumahSakit.objects.all()

    pages = Paginator(list_rumahsakit, 3)
   
    for rs in list_rumahsakit:
        content['rumah_sakit'].append({
            'name':rs.name,
            'province':rs.province,
            'address':rs.address,
            'telp':rs.telp,
           })

    page_number = request.GET.get('page')
    page_obj = pages.get_page(page_number)

    return render(request, 'rs/rs-rujukan.html',  { 'rumah_sakit' : list_rumahsakit,
        'page_obj': page_obj})

def search(request):
    search_words = request.GET.get('search')

    if search_words:
        results = RumahSakit.objects.filter(Q(province__icontains=search_words) | Q(address__icontains=search_words))
    else:
        results = RumahSakit.objects.filter(status="Published")

    pages = Paginator(results, 3)
    page_number = request.GET.get('page')
    page_obj = pages.get_page(page_number)

    content = {
        'page_obj' : page_obj,
        'search_words': search_words
    }

    return render(request, 'rs/rs-rujukan.html', content)

rs_rujukan/templates/rs/rs-rujukan.html
{% extends 'base.html' %}
{% load static %}

{% block title%}RS Rujukan{% endblock title %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'css_rs/style_rs.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock additional_css %}

{% block content %}
<div class="container">

  <div class="row justify-content-center mt-5">
    <div class="text_selector">
      Rumah Sakit Rujukan
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="text-covid">
      COVID-19
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="search-container">
      <form method="GET" action="{% url 'rs_rujukan:search' %}" >
        <input type="text" onkeydown="press(this)" placeholder="Search.." name="search" value="{{ request.GET.search }}">
        <button type="button" onclick="search()"><i class="fa fa-search" style="color: aliceblue;"></i></button>
      </form>
    </div>
  </div>

  <div class="row mt-5">
    {% if request.method == GET %}
    
    {% for rs in rs_search %}
    <div class="col-sm">
      
      <div class="card card-rs" style="width: 18rem; height: 16rem;">
      
        <div class="card-body">
          <h5> {{rs.province}} </h5>
          <div class="row">
            <div class="col-2">
              <img src="https://www.flaticon.com/svg/static/icons/svg/1546/1546074.svg" alt="hospital" style="width:25px;height:25px;">
            </div>
            <div class="col-10">
              <p class="card-title">{{ rs.name }}</p>
            </div>
          </div>
    
          <div class="row">
            <div class="col-2">
              <img src="https://www.flaticon.com/svg/static/icons/svg/2928/2928989.svg" alt="location" style="width:25px;height:25px;">
            </div>
            <div class="col-10">
              <p class="card-subtitle mb-2 text-muted">{{ rs.address }}</p>
            </div>
          </div>

          
          <div class="row">
            <div class="col-2">
              <img src="https://www.flaticon.com/svg/static/icons/svg/126/126509.svg" alt="telp" style="width:25px;height:25px;">
            </div>
            <div class="col-10">
              <p class="card-text">{{ rs.telp }}</p>
            </div>
          </div>
       
        </div>
      </div>
    </div>
    {% endfor %}

    {% else %}
    {% for rs in page_obj %}
    <div class="col-sm">
      
      <div class="card card-rs" style="width: 18rem; height: 16rem;">
      
        <div class="card-body">
          <h5> {{rs.province}} </h5>
          <div class="row">
            <div class="col-2">
              <img src="https://www.flaticon.com/svg/static/icons/svg/1546/1546074.svg" alt="hospital" style="width:25px;height:25px;">
            </div>
            <div class="col-10">
              <p class="card-title">{{ rs.name }}</p>
            </div>
          </div>
    
          <div class="row">
            <div class="col-2">
              <img src="https://www.flaticon.com/svg/static/icons/svg/2928/2928989.svg" alt="location" style="width:25px;height:25px;">
            </div>
            <div class="col-10">
              <p class="card-subtitle mb-2 text-muted">{{ rs.address }}</p>
            </div>
          </div>

          
          <div class="row">
            <div class="col-2">
              <img src="https://www.flaticon.com/svg/static/icons/svg/126/126509.svg" alt="telp" style="width:25px;height:25px;">
            </div>
            <div class="col-10">
              <p class="card-text">{{ rs.telp }}</p>
            </div>
          </div>
       
        </div>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>

  <div class="row justify-content-center mt-5">
    <nav aria-label="Page navigation">
      {% if page_obj.has_other_pages %}
      <ul class="pagination justify-content-center ">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if search_words %}&search={{search_words}} {% endif %}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active"><a class="page-link">{{ i }} <a class="sr-only">(current)</a></a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}{% if search_words %}&search={{search_words}} {% endif %}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if search_words %}&search={{search_words}} {% endif %}">Next</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link">Next</a></li>
        {% endif %}
      </ul>
      {% endif %}
    </nav>
  </div>
</div>
{% endblock content %}