beranda/urls.py
from django.urls import path
from . import views

app_name = 'beranda'

urlpatterns = [
    path('', views.home, name='home'),
    path('daftar-kritikan/', views.daftar, name='daftar'),
]

situs/urls.py
from django.urls import path

from . import views

app_name = 'situs'

urlpatterns = [
    path('', views.situs, name='situs'),
    path('savepesan/', views.pesan, name='pesan'),
]

tk1_ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beranda.urls')),
    path('rs-rujukan/', include('rs_rujukan.urls')),
    path('donasi/', include('donasi.urls')),
    path('situs/', include('situs.urls')),
]

beranda/models.py
from django.db import models

class KritikSaran(models.Model):
    nama = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    kritik_saran = models.TextField(max_length=1000)

beranda/forms.py
from django import forms
from .models import KritikSaran

class FormKritik(forms.ModelForm):
    class Meta:
        model = KritikSaran
        fields = ['nama', 'email', 'kritik_saran']

        labels = {
            'nama' : 'Nama Anda',
            'email' : 'E-mail Anda',
            'kritik_saran' : 'Pesan Anda'
        }

        widgets = {
            'nama' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'type' : 'text',
                    'placeholder' : 'Maks 100 karakter'
                }
            ),
            'email' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'type' : 'email',
                    'placeholder' : 'Ex: coformant@gmail.com'
                }
            ),
            'kritik_saran' : forms.Textarea(
                attrs = {
                    'class' : 'form-control',
                    'type' : 'text',
                    'placeholder' : 'Maks 1.000 karakter'
                }
            )
        }

beranda/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import FormKritik
from .models import KritikSaran
from django.http import HttpResponse, HttpResponseRedirect

def home(request):
    form = FormKritik(request.POST or None)
    if form.is_valid() and request.method == 'POST':
        form.save()
        messages.success(request, 'Tanggapan Anda telah kami simpan')
        return redirect('beranda:home')
        
    context = {
        'input_form' : form
    }
    return render(request, 'beranda/home.html', context)

def daftar(request):
    kritikans = KritikSaran.objects.all()
    context = {
        'daftar_kritik' : kritikans
    }
    
    return render(request, 'beranda/kritik-saran.html', context)

beranda/templates/beranda/home.html
{% extends 'base.html' %}
{% load static %}

{% block title%}Beranda{% endblock title %}

{% block additional_css %}
<link rel="stylesheet" href="{% static 'beranda/style_home.css' %}"> 
{% endblock additional_css %}

{% block content %}

<div class="jumbotron jumbotron-fluid jumbo-foto">
  <div class="container container-jumbo-foto">
    <h2 class="display-4" id="slogan">Informan <span>COVID-19</span> Anda</h2>
    <hr id="hrSlogan">
  </div>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-10 pb-4 data-container">
      <div class="row pt-4 pb-3">
        <div class="col text-center">
          <h2>Data Kasus Persebaran <span>COVID-19</span> di Indonesia</h2>
          <h6>Update Terakhir: 15 November 2020</h6>
          <h6>Sumber Data: Satuan Tugas Penangan COVID-19</h6>
        </div>
      </div>

      <div class="row">
        <div class="container" id="data">
          <div class="col text-center">
            <h3 id="header">Total Positif</h3>
            <h2 id="number">467.113</h2>
          </div>
        </div>
        <div class="container" id="data">
          <div class="col text-center">
            <h3 id="header">Total Sembuh</h3>
            <h2 id="number">391.991</h3>
          </div>
        </div>
        <div class="container" id="data">
          <div class="col text-center">
            <h3 id="header">Total Meninggal</h3>
            <h2 id="number">15.211</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid jumbo-about">
  <div class="container">
    <h1 class="display-4" id="judul">Tentang Coformant</h1>
    <hr>
    <p class="lead" id="desc">Coformant adalah sebuah platform pengumpul informasi seputar COVID-19 di Indonesia. Coformant hadir untuk Anda dan lahir dari Anda.</p>
  </div>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-10 pb-4 kritik-saran">

      <div class="row">
        <div class="container header-kritik">
          <div class="col text-center">
            <h2 id="judulKritik">Kritik & Saran</h2>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="container desc-kritik">
          <div class="col">
            <p id="descKritik">Jika terdapat kritik maupun saran terhadap konten di website kami silakan isi form di bawah ini:</p>
          </div>
        </div>
      </div>

      {% if messages %}
        {% for notif in messages %}
        <div class="alert alert-success" role="alert">
          {{ notif }}
        </div>
        {% endfor %}
      {% endif %}
      <div class="row">
        <div class="container form">
          <div class="col">
            <form method="POST">
              {% csrf_token %}

              <div class="form-group">
                <h5>{{input_form.nama.label_tag}}</h5>
                <p>{{input_form.nama}}</p>
              </div>

              <div class="form-group">
                <h5>{{input_form.email.label_tag}}</h5>
                <p>{{input_form.email}}</p>
              </div>

              <div class="form-group">
                <h5>{{input_form.kritik_saran.label_tag}}</h5>
                <p id="formKritik">{{input_form.kritik_saran}}</p>
              </div>

              <div class="container text-center">
                <input class="btn btn-success" type='submit' value='Kirim'>
                <a class="btn btn-danger ml-3" href="{% url 'beranda:daftar' %}">Lihat Kritik & Saran</a>
              </div>
              
            </form>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>
{% endblock content %}

beranda/templates/beranda/kritik-saran.html
{% extends 'base.html' %}
{% load static %}

{% block title%}Beranda{% endblock title %}

{% block additional_css %}
<link rel="stylesheet" href="{% static 'beranda/style_home.css' %}"> 
{% endblock additional_css %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-10 pb-4 kritik-saran">
    
          <div class="row">
            <div class="container header-kritik">
              <div class="col text-center">
                <h2 id="judulKritik">Daftar Kritik & Saran</h2>
              </div>
            </div>
          </div>

          {% if not daftar_kritik %}
          <div class="row">
            <div class="container daftar-kosong">
              <div class="col text-center">
                <h5>Belum ada kritik & saran yang masuk</h5>
              </div>
              <div class="container-btn text-center mt-3">
                <a class="btn btn-danger" href="{% url 'beranda:home' %}">Kembali</a>
            </div>
            </div>
          </div>

          {% else %}
          <div class="row">
              <div class="container daftar">
                  <div class="col">
                    <table class="table table-hover table-bordered">
                        <thead class="table-success thead">
                          <tr>
                            <th scope="col">Kritik & Saran dari:</th>
                            <th scope="col">Isi pesan:</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for kritik in daftar_kritik %}
                                <tr>
                                    <td>{{ kritik.nama }}</td>
                                    <td>{{kritik.kritik_saran}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="container-btn text-center mt-3">
                        <a class="btn btn-danger" href="{% url 'beranda:home' %}">Kembali</a>
                    </div>
                    
                  </div>
              </div>
          </div>

          {% endif %}

        </div>
    </div>
</div>
{% endblock content %} 