beranda/urls.py
from django.urls import path
from . import views

app_name = 'beranda'

urlpatterns = [
    path('', views.home, name='home'),
    path('daftar-kritikan/', views.daftar, name='daftar'),
]

donasi/urls.py
from django.urls import path
from . import views

app_name = 'donasi'

urlpatterns = [
    path('', views.donasi, name='donasi'),
    path('formdonasi/', views.form_donasi, name='form_donasi'),
]

rs_rujukan/urls.py
from django.urls import path

from . import views

app_name = 'rs_rujukan'

urlpatterns = [
    path('', views.index, name='index'),
    path('results', views.search, name='search')
]

situs/urls.py
from django.urls import path

from . import views

app_name = 'situs'

urlpatterns = [
    path('', views.situs, name='situs'),
    path('savepesan/', views.pesan, name='pesan'),
]

tk1_ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beranda.urls')),
    path('rs-rujukan/', include('rs_rujukan.urls')),
    path('donasi/', include('donasi.urls')),
    path('situs/', include('situs.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}Coformant{% endblock title %}</title>
  
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/stylebase.css' %}">
  {% block additional_css %}
  {% endblock additional_css %}

  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>

<body class="d-flex flex-column min-vh-100">
  <div class="navigation">
    <div class="menu-bar">
      <nav class="navbar navbar-expand-lg navbar-light">
        <img src="{% static 'img/CoformantLogo.png' %}">
        <a class="navbar-brand" href="#">COFORMANT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-link active" href="{% url 'beranda:home' %}">Beranda</a>
            <a class="nav-link" href="{% url 'donasi:donasi' %}">Donasi</a>
            <a class="nav-link" href="{% url 'rs_rujukan:index' %}">RS Rujukan</a>
            <a class="nav-link" href="{% url 'situs:situs' %}">Daftar Situs</a>
          </div>
        </div>
      </nav>
    </div>
    
  </div>
  
  {% block content %}
  {% endblock content %}
  <footer class="mt-auto">
    <div class="container-footer">
      <p>Kelompok E10 PPW - &copy; Copyright 2020. All Rights Reserved.</p>
    </div>
  </footer>
</body>



</html>