donasi/urls.py
from django.urls import path
from . import views

app_name = 'donasi'

urlpatterns = [
    path('', views.donasi, name='donasi'),
    path('formdonasi/', views.form_donasi, name='form_donasi'),
]

situs/urls.py
from django.urls import path

from . import views

app_name = 'situs'

urlpatterns = [
    path('', views.situs, name='situs'),
    path('savepesan/', views.pesan, name='pesan'),
]

tk1_ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beranda.urls')),
    path('rs-rujukan/', include('rs_rujukan.urls')),
    path('donasi/', include('donasi.urls')),
    path('situs/', include('situs.urls')),
]

donasi/models.py
from django.db import models

# Create your models here.
class fitur_donasi(models.Model):
    nama_donasi = models.CharField(max_length=100)
    nama_pemberi = models.CharField(max_length=100)
    url = models.CharField(max_length=100)

    def __str__(self):
        return self.nama_donasi

donasi/forms.py
from django import forms

from donasi.models import fitur_donasi

class DonasiForm(forms.Form):
    nama_donasi = forms.CharField(label='Nama Donasi :', max_length=50,
                                    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ex: Donasi RS Harapan Ibu'}), required=True)

    nama_pemberi = forms.CharField(label='Author :', max_length=50,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ex: Nama anda/institusi/organisasi/dll'}), required=True)

    url = forms.CharField(label='URL Donasi :', max_length=50,
                                    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'masukkan URL'}), required=True)

donasi/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from donasi.models import fitur_donasi
from .forms import DonasiForm
from .models import fitur_donasi

# Create your views here.
def form_donasi(request):
    data_donasi = fitur_donasi.objects.all()
    form = DonasiForm(request.POST or None)
    donate_context = {
        'data_donasi' : data_donasi,
        'form' : form,
    }
    if request.method == "POST":
        if form.is_valid():
            data_donasi.create(
                nama_donasi = form.cleaned_data.get('nama_donasi'),
                nama_pemberi = form.cleaned_data.get('nama_pemberi'),
                url = form.cleaned_data.get('url'),
            )
            return redirect('/donasi')

    return render(request, 'formdonasi.html', donate_context)

def donasi(request):
    tambah_link = DonasiForm()
    data = fitur_donasi.objects.all()
    response = {
        'tambah_link': tambah_link,
        'data': data,
    }
    return render(request, 'donasi.html', response)

donasi/templates/donasi.html
{% extends 'base.html' %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}List Donasi{% endblock title %}</title>

        {% block additional_css %}
        <link rel="stylesheet" href="{% static 'style_donasi.css' %}"> 
        {% endblock additional_css %}

    </head>

    {% block content %}
    <div class="jumbotron jumbotron-fluid fotonya">
        <div class="container-fluid csatu">
            <h1 style="text-shadow: 2px 2px 10px #000000;"><b>DONASI</b></h1>
            <hr>
            <h3 id = "hsatu">Daftar Program Donasi<span><b> COVID-19</b></span></h3>
        </div>
    </div>

    <div class="text-center">
        <h5>Untuk berdonasi, pilih program yang kamu inginkan di bawah ini</h5><br>
    </div>

    <!-- Show result -->
    <div class="row">
        {% for kegiatan in data %}
        <div class="col-md-4 mb-4 area">
            <div class="card cardku" style="max-width: 22rem; text-align: center; margin: 0 auto; float: none; margin-bottom: 10px;">
                <!-- card header -->
                <div class="card-header" style="font-weight: bold; background-color: #FFEFCA;">
                    <h5 class="card-title" style="color: #006876; font-weight: bold;">{{ kegiatan.nama_donasi }} </h5>
                </div>
                <div class="card-body">
                    <p style="font-weight: bold;">oleh {{ kegiatan.nama_pemberi }}</p>
                    <a href="{{ kegiatan.url }}" class="btn btn-primary btnijo">Lihat lebih lanjut</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

        <div class="text-center back">
            <h5 style="padding-bottom: 0.694vw;">Ingin menambahkan donasi?</h5>
            <a class="btn btn-primary btnbawah" href=" {% url 'donasi:form_donasi' %}" role="button">Tambah donasi</a><br>
        </div>
        <br>
    
    {% endblock content %}

donasi/templates/formdonasi.html
{% extends 'base.html' %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Form Donasi{% endblock title %}</title>

        {% block additional_css %}
        <link rel="stylesheet" href="{% static 'style_donasi2.css' %}"> 
        {% endblock additional_css %}

    </head>

    {% block content %}
    <!-- Form -->
    <div class="card mt-4 mb-5 shadow-sm rounded formbawah">
        <div class="card-body" id="tambahdonasi">
            <h3 class="text-center tambahdonasiTitle"><b>Tambahkan Donasi</b></h3><hr><br>
            <p class="text-center" style="padding-bottom: 1.042vw;">Terima kasih, orang baik! 😊</p>
            <div class="col-6" style="margin-left: 25%">
                <form class="d-flex flex-column my-2 w-90" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <p class="w-100 justify-content-center my-1" style="padding-bottom: 0.694vw;"><b>{{ field.label }}</b><br> {{ field }}</p>
                    {% endfor %}
                    <button type="submit" value="Submit" class="btn btn-primary btnijo">Submit</button>
                </form>
            </div>
        </div>
    </div>

    <div class="back text-center">
        <a class="btn btn-primary btnbawah" href="/donasi" role="button">Kembali ke daftar donasi</a>
    </div>
    {% endblock content %}